name: server_lms_smuct
version: 1.0.0
description: A new Get Server application.
environment: 
  sdk: '>=2.0.11 <3.0.0'

dependencies: 
  get_server: 1.2.1
  http: 0.13.4
  path_provider: ^2.0.11

dev_dependencies: 
  pedantic: 1.11.1
  test: 1.21.3

